### ISSUE TITLE
Plugin should only select fully matching items

### ISSUE THREAD

**Issue by zedtux** [richrace/highlight-selected#101]
```
$ atom --version
1.0.11
$ apm list | grep atom-lint
$
```
I do not have any Use React Editor option in Atom.

Here is a screenshot of what I mean:

![atom_highlight-selected](https://cloud.githubusercontent.com/assets/478564/9734622/ce424fb0-5634-11e5-9732-d961b6111dc6.png)

Selecting `notification_written_notice` should not highlight `notification_written_notice_id`.

**Comment by richrace** [comment]
Do you have in the plugin settings, "Only Highlight Whole Words" option ticked?

**Comment by zedtux** [comment]
... nice ! :)

Shouldn't this be ticked by default ?

**Comment by richrace** [comment]
It will be default in an upcoming release.

**Comment by zedtux** [comment]
:+1:
