### ISSUE TITLE
Performance on large files

### ISSUE THREAD

**Issue by peppy** [richrace/highlight-selected#104]
On a file with 120k lines, selecting a word present on every line will hang the editor for over 30 seconds. Would be nice to have some kind of timeout/limiting mechanism to avoid this kind of thing.

Case in point: happens with dates on logfiles

**Comment by richrace** [comment]
There is a timeout in the settings. And hopefully with Atom 1.3 the marker API should become faster.

**Comment by peppy** [comment]
The timeout in the setting isn't actually a timeout but a delay (until the searching starts). It should probably be renamed as such. By timeout I mean an "abort mission!" when the highlighting takes over n seconds. Alternatively, you could add a limit of number-of-lines to search in either direction from the current cursor position.

**Comment by tomByrer** [comment]
@peppy How long does a normal search ("Find in Buffer") take for these files?

**Comment by andrea-capri** [comment]
Any progress on this? I've moved to using another plugin that does has decent performance on large files but has less options.
