### ISSUE TITLE
Doesn't work for unicode words

### ISSUE THREAD

**Issue by ebugusey** [richrace/highlight-selected#105]
Atom 1.2.2
package version 0.11.1

Highlighting doesn't work for at least Cyrillic symbols.
Example:
![english](https://cloud.githubusercontent.com/assets/8318227/11295146/ac38ea96-8f82-11e5-81a5-494841834ce8.png)
![cyrillic](https://cloud.githubusercontent.com/assets/8318227/11295147/ae9f5f0e-8f82-11e5-9a89-15b3d288dd8b.png)

**Comment by richrace** [comment]
I think I need to use a different Regex Engine that supports Unicode.

E.g. https://github.com/atom/autocomplete-plus/issues/76

**Comment by ebugusey** [comment]
Isn't es6 implements /u flag for regex?

**Comment by vkotovv** [comment]
Duplicate https://github.com/richrace/highlight-selected/issues/153

**Comment by vkotovv** [comment]
@richrace Autocomplete-plus now supports Unicode, see merged PR https://github.com/atom/autocomplete-plus/pull/667.

**Comment by UserQuestions** [comment]
Is there any update on this?  Thanks!

**Comment by richrace** [comment]
See #174
