### ISSUE TITLE
Missing highlight when line is folded

### ISSUE THREAD

**Issue by diesire** [richrace/highlight-selected#108]
``` bash
λ atom -v
1.4.0-beta0
λ apm list | grep highlight-selected
├── highlight-selected@0.11.1
```

When a line is folded, highlight count it's OK, but the selection is not highlighted

```
CREATE TABLE t1
  (
    field1,
    field2
  );
CREATE TABLE t2 AS
  SELECT * FROM t1;
CREATE TABLE t3 AS
  SELECT * FROM t1;
```

![image](https://cloud.githubusercontent.com/assets/1185591/11810832/8ebd3900-a331-11e5-999b-c8b0b6df9a42.png)

**Comment by MartinMuzatko** [comment]
I also miss this feature. Probably there are some issues to write this functionality, since you can't manually select the line that is folded.

**Comment by richrace** [comment]
The decorations get removed so it may be an issue with Atom Core.

**Comment by diesire** [comment]
Sorry @richrace, I forgot the issue
It works

![image](https://cloud.githubusercontent.com/assets/1185591/24552438/b5ed2e90-1626-11e7-95b8-8525a19678f2.png)

Thanks! :+1:
