### ISSUE TITLE
Highlight any selection (without double-clicking)

### ISSUE THREAD

**Issue by tonn** [richrace/highlight-selected#113]
Double-clicking - select whole word, but sometimes I need to find part of word and I cant select this part by double clicking

**Comment by richrace** [comment]
If you disable the setting `Only highlight whole words` it should highlight any text that you select that is repeated.

**Comment by lucas-nelson** [comment]
I think this is referring to some behaviour I've seen too. `Only highlight whole words` is *disabled* in this scenario.

1. Looking at some Ruby code with a bunch of "something.new" code

2. Double click the 'new' and all the instances of 'new' in the file are highlighted - good!
![image](https://cloud.githubusercontent.com/assets/5751835/17389051/05a00eca-5a44-11e6-884b-2a1b385d35ed.png)

3. Highlight 'new' one character-at-a-time and there are no highlights until all three letters are selected
![image](https://cloud.githubusercontent.com/assets/5751835/17389057/1735d96c-5a44-11e6-8513-0326dd8b4406.png)

4. Include the leading '.' in the selection: '.new' and no other instances of '.new' are highlighted
![image](https://cloud.githubusercontent.com/assets/5751835/17389063/2249d448-5a44-11e6-854f-d329d64950d7.png)

It would be nice to highlight partial bit of words and have the highlights fire off. Maybe after a short delay in the selected text changing so people's screen don't start flashing at them?

This behaviour is unrelated to the `Only highlight whole words`. This one feels like it's about *when* the highlighting gets turned on, not the decision about which matches to show.

PS: awesome Atom package, thank you so much for the contribution.

**Comment by tonn** [comment]
I see now highlight is not related to double click event. It's great ))
