### ISSUE TITLE
[Suggestion] Match only whole word

### ISSUE THREAD

**Issue by tinymins** [richrace/highlight-selected#116]
Is there any options for match only whole word?
![image](https://cloud.githubusercontent.com/assets/1808990/13454823/9743cd50-e094-11e5-8420-84a9490fde0d.png)
For example, I double click the word `tRecipe`, actually I just want to highlight all `tRecipe` but not `l_tRecipe`. But currently, all of those words are highlighted.

That is.
Thanks~

**Comment by richrace** [comment]
In the settings there should be the option to match whole word.

-- 
Richard Race

**Comment by tinymins** [comment]
![image](https://cloud.githubusercontent.com/assets/1808990/13455146/8cab8bd8-e096-11e5-8c2d-779f8db07cea.png)
![image](https://cloud.githubusercontent.com/assets/1808990/13455155/990e5144-e096-11e5-9347-438e5ab9d481.png)
Saw it in config code but not found in setting page 0.0

**Comment by tinymins** [comment]
Umm I found. But why it is checked and I can see not only whole word highlighted

**Comment by tinymins** [comment]
... Sorry I found that I've installed another package named Selection Highlight.

**Comment by richrace** [comment]
Have you just installed it?

If yes, have you restarted Atom?

If not, and have you restarted Atom between when you installed it and now?


-- 
Richard Race

**Comment by tinymins** [comment]
Yeah I just installed it, and now it works well. Thanks~

btw, do you know how to make `ctrl-d` select only next whole word?

Eg: I want to select next `max`, but not want `maxLevel`. But when I press `ctrl-d`, `max` in `maxLevel` will also get selected.
I try to find some solution on google but failed. :-(
