### ISSUE TITLE
Word-boundaries not in line with language settings

### ISSUE THREAD

**Issue by fkm** [richrace/highlight-selected#117]
HI there :-)

I changed the "Non Word Characters" for language-javascript to exclude the dollar sign. Unfortunately, highlight-selected doesn't trigger anymore when I select my jQuery node variables.

I think the line responsible is:
https://github.com/richrace/highlight-selected/blob/master/lib/highlighted-area-view.coffee#L87

As, at the moment, I don't know enough about how Atom works I just report this here for when I do :-)

Cheers, Florian

**Comment by richrace** [comment]
See #174
