### ISSUE TITLE
Deprecated selector in `highlight-selected/styles/highlight-selected.less`

### ISSUE THREAD

**Issue by Nikki1993** [richrace/highlight-selected#131]
In `highlight-selected/styles/highlight-selected.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
- `:host atom-text-editor .highlight.highlight-selected .region,
  atom-text-editor atom-text-editor .highlight.highlight-selected .region,
  atom-text-editor::shadow atom-text-editor .highlight.highlight-selected .region` => `:host atom-text-editor .highlight.highlight-selected .region,
  atom-text-editor atom-text-editor .highlight.highlight-selected .region,
  atom-text-editor atom-text-editor .highlight.highlight-selected .region`
- `:host .highlights .highlight-selected .region,
  atom-text-editor .highlights .highlight-selected .region,
  atom-text-editor::shadow .highlights .highlight-selected .region` => `:host .highlights .highlight-selected .region,
  atom-text-editor .highlights .highlight-selected .region,
  atom-text-editor .highlights .highlight-selected .region`
- `:host .highlights .highlight-selected .region,
  atom-text-editor .highlights .highlight-selected .region,
  atom-text-editor::shadow .highlights .highlight-selected .region` => `:host .highlights .highlight-selected .region,
  atom-text-editor .highlights .highlight-selected .region,
  atom-text-editor .highlights .highlight-selected .region`
- `:host .highlights .highlight-selected.background .region,
  atom-text-editor .highlights .highlight-selected.background .region,
  atom-text-editor::shadow .highlights .highlight-selected.background .region` => `:host .highlights .highlight-selected.background .region,
  atom-text-editor .highlights .highlight-selected.background .region,
  atom-text-editor .highlights .highlight-selected.syntax--background .region`
- `:host .highlights .highlight-selected.light-theme .region,
  atom-text-editor .highlights .highlight-selected.light-theme .region,
  atom-text-editor::shadow .highlights .highlight-selected.light-theme .region` => `:host .highlights .highlight-selected.light-theme .region,
  atom-text-editor .highlights .highlight-selected.light-theme .region,
  atom-text-editor .highlights .highlight-selected.light-theme .region`
- `:host .highlights .highlight-selected.light-theme.background .region,
  atom-text-editor .highlights .highlight-selected.light-theme.background .region,
  atom-text-editor::shadow .highlights .highlight-selected.light-theme.background .region` => `:host .highlights .highlight-selected.light-theme.background .region,
  atom-text-editor .highlights .highlight-selected.light-theme.background .region,
  atom-text-editor .highlights .highlight-selected.light-theme.syntax--background .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Computero** [comment]
Any updates on this issue?

**Comment by davherrmann** [comment]
I think #136 will fix this – maybe wait for Atom 1.13 stable? See [When should I migrate my package?](http://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles/#when-should-i-migrate-my-themepackage)

**Comment by SirWaddles** [comment]
1.13 is now the main stable release

**Comment by aadityamaheshwari** [comment]
I am on stable 1.13.0 (latest MacOS) and can confirm issue still exists.

**Comment by cliffordfajardo** [comment]
Also getting deprecation alerts from Atom & I'm on 1.13.0

**Comment by Kerwood** [comment]
Still Waiting

**Comment by richrace** [comment]
Waiting for https://travis-ci.org/richrace/highlight-selected/jobs/191092635 to pass...

**Comment by Computero** [comment]
Looks like just about all the 3rd party extensions are broken. I have seen several already that are getting the same error...

**Comment by richrace** [comment]
Could you please share any 3rd party extensions. I'm only aware of [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected)

**Comment by Kerwood** [comment]
Mine updated just fine yesterday
