### ISSUE TITLE
$variables cannot be highlighted

### ISSUE THREAD

**Issue by Edeph** [richrace/highlight-selected#132]
example : 
`my $rev = $ARGV[1];
my $prev_rev = $rev-1;
`
$prev and $prev_rev won't be highlighted throughout the document

**Comment by phorust** [comment]
Came here to report this... seems like the same issue as #141
to clarify, when selecting `$this`, no other occurrences of `$this` are highlighted. but, when selecting `this`, the other `this` are highlighted. pretty minor issue but a bit annoying for php, as all variables start with `$`

**Comment by richrace** [comment]
See #174
