### ISSUE TITLE
Deprecated selector in `highlight-selected\styles\highlight-selected.less`

### ISSUE THREAD

**Issue by sbistrovic** [richrace/highlight-selected#134]
In `highlight-selected\styles\highlight-selected.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host atom-text-editor .highlight.highlight-selected .region,
atom-text-editor atom-text-editor .highlight.highlight-selected .region,
atom-text-editor::shadow atom-text-editor .highlight.highlight-selected .region` => `:host atom-text-editor .highlight.highlight-selected .region,
atom-text-editor atom-text-editor .highlight.highlight-selected .region,
atom-text-editor.editor atom-text-editor .highlight.highlight-selected .region`

* `:host .highlights .highlight-selected .region,
atom-text-editor .highlights .highlight-selected .region,
atom-text-editor::shadow .highlights .highlight-selected .region` => `:host .highlights .highlight-selected .region,
atom-text-editor .highlights .highlight-selected .region,
atom-text-editor.editor .highlights .highlight-selected .region`

* `:host .highlights .highlight-selected .region,
atom-text-editor .highlights .highlight-selected .region,
atom-text-editor::shadow .highlights .highlight-selected .region` => `:host .highlights .highlight-selected .region,
atom-text-editor .highlights .highlight-selected .region,
atom-text-editor.editor .highlights .highlight-selected .region`

* `:host .highlights .highlight-selected.background .region,
atom-text-editor .highlights .highlight-selected.background .region,
atom-text-editor::shadow .highlights .highlight-selected.background .region` => `:host .highlights .highlight-selected.background .region,
atom-text-editor .highlights .highlight-selected.background .region,
atom-text-editor.editor .highlights .highlight-selected.syntax--background .region`

* `:host .highlights .highlight-selected.light-theme .region,
atom-text-editor .highlights .highlight-selected.light-theme .region,
atom-text-editor::shadow .highlights .highlight-selected.light-theme .region` => `:host .highlights .highlight-selected.light-theme .region,
atom-text-editor .highlights .highlight-selected.light-theme .region,
atom-text-editor.editor .highlights .highlight-selected.light-theme .region`

* `:host .highlights .highlight-selected.light-theme.background .region,
atom-text-editor .highlights .highlight-selected.light-theme.background .region,
atom-text-editor::shadow .highlights .highlight-selected.light-theme.background .region` => `:host .highlights .highlight-selected.light-theme.background .region,
atom-text-editor .highlights .highlight-selected.light-theme.background .region,
atom-text-editor.editor .highlights .highlight-selected.light-theme.syntax--background .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by denlaku** [comment]
hi
