### ISSUE TITLE
Selection not highlighted when hardware acceleration is disabled

### ISSUE THREAD

**Issue by gsongsong** [richrace/highlight-selected#146]
I am using Atom on Ubuntu installed via VirtualBox with the following commands `$ atom --disable-gpu`.
I disable hardware acceleration because VirtualBox has known issues with it, for example, https://discuss.atom.io/t/atom-wont-open-on-ubuntu-16-04-1/32026

With GPU acceleration disabled, `highlight selected` package does not work properly.
No highlight boxes around selection appear.

This is not a problem on Windows or Mac which I use. If you have more information to solve, please let me know.

Regards.

**Comment by melankh** [comment]
It seems that this issue happens also when atom is launched on Windows via Remote Desktop (rdp, citrix...).

The trick `--disable-gpu` works for me ! Thanks a lot.
