### ISSUE TITLE
Highlight Background Only on Selected Words

### ISSUE THREAD

**Issue by pingshunhuangalex** [richrace/highlight-selected#151]
The `highlight background` option really comes in handy as it adds more contrast to the selection. However, I notice I can only hide highlight on selected word...

Just wonder if it's possible to Show highlight background on selected words. Thanks.

**Comment by Shirimasen** [comment]
This is how I setup highlight-selected. Is that what you want?
![screen shot 2017-06-01 at 22 39 11](https://cloud.githubusercontent.com/assets/24192094/26699759/2ed75798-471b-11e7-978e-ef4ffd9a15fc.png)
![screen shot 2017-06-01 at 22 39 05](https://cloud.githubusercontent.com/assets/24192094/26699760/2ed894d2-471b-11e7-8b05-0e09f77dd861.png)

**Comment by pingshunhuangalex** [comment]
@Shirimasen Not quite, but nice font there.

What I'm after is actually an option opposite to the first one, something like `Only show highlight on selected word`
