### ISSUE TITLE
 Chinese character cannot be highlighted

### ISSUE THREAD

**Issue by gmx321** [richrace/highlight-selected#153]
Hello!

Chinese character cannot be highlighted. But if the block including Chinese characters is **ended with letter or mumber**, it can be highlighted.

Could you help me? Thanks.

![image](https://user-images.githubusercontent.com/7112268/27322213-cf8d4af4-55cf-11e7-9640-7c78587a3ecd.png)

An example is provided for test: 

>CS金叉:=(REF(C,1)<REF(MABS,1) && C>MABS);
CS死叉:=(REF(C,1)>REF(MABS,1) && C<MABS) ;
CS金叉间隔12:=BARSLAST(CS金叉);
CS死叉间隔AB:=BARSLAST(CS死叉);
CS金叉间隔:=BARSLAST(CS金叉间隔12);
CS死叉间隔:=BARSLAST(CS死叉间隔AB);

**Comment by gmx321** [comment]
the same blocks are in same color:

![image](https://user-images.githubusercontent.com/7112268/27324544-239fbfca-55d8-11e7-8730-b5c62be61e08.png)

**Comment by ion201** [comment]
The pull request I recently made incidentally resolves this issue: https://github.com/richrace/highlight-selected/pull/154

**Comment by gmx321** [comment]
Thank you very much!

**Comment by richrace** [comment]
See #174
