### ISSUE TITLE
feature: show highlights in scrollbar

### ISSUE THREAD

**Issue by Yarden92** [richrace/highlight-selected#155]
can you add feature for showing the selected words on the scrollbar?
Same way google use it:

![image](https://user-images.githubusercontent.com/19271465/27584241-e9101086-5b3f-11e7-8866-c14a5fc6325a.png)

or any other code editor like Notepad++, VS, Android Studio, and so on..

alternatively, merge with [scroll-searcher](https://atom.io/packages/scroll-searcher).

**Comment by willaleksander** [comment]
I was searching for this right now, it's a important feature

**Comment by hofi-jus** [comment]
In a long html file I double click body tag, and than want to scroll with scrollbar, selection of body has been removed.

Would be also great if it will be mark until the next click in editor field not on scrollbar.
BTW
With scrollbar highlighting it would be more awesome.

**Comment by jimmyadaro** [comment]
I really need this.

**Comment by twifty** [comment]
I don't know if this project has been abandoned or not. No updates for quite some time.

I would also like this feature. And, to take it one step further, perhaps display which collapsed code blocks contain the selected word.

**Comment by richrace** [comment]
This project has not been abandoned - it works for my needs.

I've been following https://github.com/atom/find-and-replace/issues/529 to see if there would be something I could port here.

**Comment by surdu** [comment]
@richrace As I mentioned in the find-and-replace issue, I've created [scroll-marker](https://atom.io/packages/scroll-marker) that uses [Atom Services API](http://blog.atom.io/2015/03/25/new-services-API.html) to provide a service that other packages can consume in order to put markers on the scroll bar.

It's still young, documentation is pending, but I believe it can help you or someone else interested in fixing this issue.

**Comment by richrace** [comment]
Closed via da49054368ccdc3aecd810498e9f1abc21431ea2

**Comment by surdu** [comment]
@richrace Please comment here when you publish this feature and I will list the package in the [scroll-marker packages list](https://github.com/surdu/scroll-marker#packages-powered-by-scroll-marker). If it's ok with you, of course :)

**Comment by richrace** [comment]
🎉 Version 0.14.0 has scroll marker support
