### ISSUE TITLE
Cyrillic letters

### ISSUE THREAD

**Issue by AlekseyGur** [richrace/highlight-selected#157]
Hi!
Thank you very much for that package! It is very useful. But could you add support of cyrillic letters?
It is possible to highlit latin alphabet, but not cyrillic. You can double click "word" in this code:
```
<span>word</span> 
<span>word</span> 
```
![image](https://user-images.githubusercontent.com/30201077/28275155-b56ec77c-6b1b-11e7-9686-0e046cdd57eb.png)
and you'll highlite both "word". But if you write it in cyrillic letters, then it doesn't work:
```
<span>слово</span> 
<span>слово</span> 
```
![image](https://user-images.githubusercontent.com/30201077/28275172-c17144f0-6b1b-11e7-8621-2176a3d18201.png)

Best regards, 
Alex

**Comment by klicperajo** [comment]
This issue seems to occur for any Unicode letters. I've recently seen it with greek (e.g. α0) and accented letters (lá).

**Comment by richrace** [comment]
See #174
