### ISSUE TITLE
Option to highlight one-letter variables

### ISSUE THREAD

**Issue by vkotovv** [richrace/highlight-selected#170]
Example (C++ code):
```
std::vector<std::string> v;
// more code here
return v;
```
It will not highlight the occurences of `v` variable if I select it (I guess because it is not a word). But it will be good if there is an option to highlight one-char variables too.

**Comment by richrace** [comment]
There is a setting `Minimum Length`. The default is 2 characters, you can change it to 1. But that might have performance issues.

**Comment by vkotovv** [comment]
@richrace Thanks for the info.
