### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by richrace** [richrace/highlight-selected#174]
Hi, 

I was wondering if someone could test out the latest master? (I haven't published a new package)

Main changes: 
- I've removed the regex word boundary so unicode characters will work with `Only Highlight Whole Words` 
- Added a setting for non-word characters to ignore so `$ @ %` will work for PHP, Perl etc. with `Only Highlight Whole Words` set. This should make it easier to add new ones.

Thanks!

/cc @krasnovpro @vkotovv @UserQuestions @mj41 @fkm @phorust  @Edeph @mindrones @tonn @jonkwheeler  @AlekseyGur  @klicperajo  @Wigginns @ion201 @zertosh

**Comment by ion201** [comment]
Thanks @richrace, works well for me; and I'd never complain about more customization options. Also, looks like this TODO in the readme has been answered:

> Should we highlight symbols?

**Comment by mindrones** [comment]
Hi, sure how so? (never installed a package from git)

**Comment by richrace** [comment]
@mindrones 

```terminal
$ apm dev highlight-selected
$ atom --dev ~/some/folder/with/code
$ atom  ~/some/folder/with/code
```

And one window should highlight things you want and one won't. And I hope no error! 😄

**Comment by mindrones** [comment]
Sorry Richard, got swamped at work... The new version is super thank you!

**Comment by Wigginns** [comment]
Sorry I missed this. This works perfectly, thanks much.
