### ISSUE TITLE
Selected tab and space

### ISSUE THREAD

**Issue by sanada01** [richrace/highlight-selected#182]
If I select spaces and tabs, then the atom often gets stuck.
Version: 0.14.0

![kijeloles_bug](https://user-images.githubusercontent.com/28780118/43584412-9b4960b4-9662-11e8-8a07-32172fb7bb4f.gif)

**Comment by richrace** [comment]
This happens only when `Only Highlight Whole Words` is set to `false`

**Comment by sanada01** [comment]
Thanks you. ;)
