### ISSUE TITLE
*BUG* Atom v1.48.0 (2020-06-10) Broke this Package.

### ISSUE THREAD

**Issue by Zwalraven** [richrace/highlight-selected#218]
With Atom v1.48.0 you can now only highlight single words with this package. I wanted to bring that to your attention so you can fix the problem. I am not educated enough in code to report to you why it is doing this, I just know I rolled back to 1.47.0 and it works again. Thank you for your time, and thank you for this Package. It is the #1 package I use in Atom. It helps me immensely.

**Comment by Zwalraven** [comment]
Bump, just wanted to know someone is aware of this?

**Comment by richrace** [comment]
I believe you're interested in this Fork https://github.com/nathanpotolsky/highlight-selected @nathanpotolsky

**Comment by Zwalraven** [comment]
Looks like the guy who did it is MIA. Is there any change this function 
could be updated to work with new versions on Atom?
