### ISSUE TITLE
Minimum length

### ISSUE THREAD

**Issue by BlaM** [richrace/highlight-selected#36]
It would be nice to have an option to highlight only if the selection has more than X characters. Otherwise selecting a single letter can cause excessive highlighting (and slowdown) in big documents.

**Comment by richrace** [comment]
Ok. Basically, just need to change this check. 

https://github.com/richrace/highlight-selected/blob/master/lib/highlighted-area-view.coffee#L40-42

`result.length is 0` to `result.length < config.minimumLength` or something like that. 

Shouldn't be too hard.
