### ISSUE TITLE
Styling has no effect on highlighting

### ISSUE THREAD

**Issue by rnyberg** [richrace/highlight-selected#41]
My (complete) styles.less:

     .editor {
       // Box
       .highlight-selected .region {
         border-color: rgba(210, 210, 210, 0.3);
       }
       // Background
       .highlight-selected.background .region {
         background-color: rgba(155, 155, 155, 0.3);
       }
       // Light theme box (set in settings)
       .highlight-selected.light-theme .region {
         border-color: rgba(90, 90, 90, 0.3);
       }
       // Light theme background (set in settings)
       .highlight-selected.light-theme.background .region {
         background-color: rgba(0,0,0, 0.4);
       }
     }

    .tree-view {

    }

    // style the background and foreground colors on the atom-text-editor-element
    // itself
    atom-text-editor {

    }

    // To style other content in the text editor's shadow DOM, use the ::shadow
    // expression
    atom-text-editor::shadow .cursor {

    }

Toggling the BG checkbox works and so does toggling the Light mode, but for some reason overriding the styles isn't working. I've tried reloading Atom and restarting, no effect.

OS: Ubuntu 14.04

**Comment by tylerdiaz** [comment]
Noticed this as well. If you change `atom-text-editor` to be `atom-text-editor, atom-text-editor::shadow` instead it should work again.

I've opened up a PR for this: https://github.com/richrace/highlight-selected/pull/51

**Comment by richrace** [comment]
@tylerdiaz PR should fix this. Just replace `.editor` to `atom-text-editor::shadow`
