### ISSUE TITLE
Only highlight matches when they are whole words

### ISSUE THREAD

**Issue by secrettriangle** [richrace/highlight-selected#59]
When I select `C` in my code, I see that the "C" in `Conn` is also highlighted. This would make a minimal amount of sense if *any* selection highlighted matches; however, since this package only highlights matches if a whole word is selected, it only makes sense that only whole-word matches should be highlighted.

**Comment by richrace** [comment]
There's a setting for only highlighting whole words.

**Comment by secrettriangle** [comment]
Maybe it should be this way by default?
