### ISSUE TITLE
can't see which ones are selected

### ISSUE THREAD

**Issue by hawsome** [richrace/highlight-selected#71]
After I select something I usually do `cmd+d` to select them one by one, but when I do it with this plugin, I can't see which ones are highlighted or not.

**Comment by richrace** [comment]
`cmd+d` is from the `find-and-replace` package. `cmd+d` selects (adds a new cursor) at the next occurrence of the selection, removing the highlight box.

There is a setting `Hide highlight on selected word` in the `highlight-selected` settings which stops this from happening.

**Comment by hawsome** [comment]
OMG. Why didn't I click 'settings' from the get-go...?

**Comment by richrace** [comment]
:+1:
