### ISSUE TITLE
Whole Words option should support the "$" symbol for PHP files

### ISSUE THREAD

**Issue by ShimShamSam** [richrace/highlight-selected#73]
A recent change in Atom has made double-clicking a word select it *including the dollar sign*. This makes the Whole Words option ignore the word and fail to highlight matches.

**Comment by richrace** [comment]
Can you check what your `Non Word Characters` are in settings please?

**Comment by richrace** [comment]
So you'd expect all the `test` below to be highlighted (and not the last one):

```php
$test = "test"
// Some test file
// Don't highlight thistest
```

**Comment by ShimShamSam** [comment]
@richrace You are correct. Where can I find Non-Word Characters setting? I do not see an option for it.

**Comment by MineyMe** [comment]
I came here to report the same issue. The change to include the dollar sign in the selection in itself doesn't seem entirely illogical (the variable name includes the dollar, after all), but it made using this extension to quickly see occurrences of a variable very impractical by requiring that you only select the portion after the dollar sign.
