### ISSUE TITLE
Only highlight after timeout

### ISSUE THREAD

**Issue by fbender** [richrace/highlight-selected#75]
Instead of highlighting instantly (on each selection change), I'd like the plugin to only highlight the words after timeout (e.g. 500ms, preferably configurable). This reduces visual as well as computational load.

**Comment by richrace** [comment]
:+1:

**Comment by fbender** [comment]
Awesome, thanks! :)

**Comment by fbender** [comment]
Works perfectly! Thanks a lot!

**Comment by richrace** [comment]
:+1: :smile: Good to hear.
