### ISSUE TITLE
Highlight Line Numbers also when selected ( enhancement )

### ISSUE THREAD

**Issue by shanalikhan1** [richrace/highlight-selected#76]
There should be a bar with window size in whole window size and when the word is selected  appear when the word is selected the area of those words in whole document should be generated and appear in the some portion of that bar. when scroll bar gets near to that highlighted area of bar the document will be scrolled to show that line 
Example is in visual studio ( NOT CODE ) Standard or premium when any word is selected there is blue or pink sign appear 
Example when any word is find on IE 11 degugging tool the whole document gets mark on those areas near scroll bar where the word exists. like in picture attached blue bars
![capture](https://cloud.githubusercontent.com/assets/8774556/7959041/e01c947e-0a0e-11e5-82fe-a46b3f7a24dd.PNG)

**Comment by richrace** [comment]
Does using https://github.com/atom-minimap/minimap and https://github.com/atom-minimap/minimap-highlight-selected satisfy your needs or do you want something more minimal?

**Comment by shanalikhan1** [comment]
yes thanks its completing the purpose but it would be good if there is function like shown in picture more minification near scroll and shades only

**Comment by leooon** [comment]
+1 for marks on scroll bar, like Chrome does. It was the feature I most missed migrating from Brackets.

**Comment by shanalikhan1** [comment]
is it possible to set the highlighted positions in the scroll bar in Atom ? like the picture.
