### ISSUE TITLE
Highlight not always working with double click to select word

### ISSUE THREAD

**Issue by lexicalunit** [richrace/highlight-selected#77]
Highlight selected doesn't seem to always work when you double click on a word to select it.

![out](https://cloud.githubusercontent.com/assets/1903876/8063845/aa41ea7e-0e9c-11e5-9b80-ec07bcace563.gif)

> gif showing double clicking on `items` doesn't highlight other instances of that token in the buffer. Yet double clicking on `originalPrice` *does* work. Then using the keyboard to select `items` works.

```
$ atom --version
0.207.0
$ apm list | grep lint
├── linter@0.12.6
```

**Comment by richrace** [comment]
Is that `PHP`?

**Comment by lexicalunit** [comment]
@richrace Yes, it's PHP. I feel like I've seen the issue in other source grammars too, but I can't reproduce it now in some other sources I'm currently working with.

**Comment by casbreuk** [comment]
It doesn't work at all in C#

**Comment by richrace** [comment]
Do you have some example code that demonstrates your issue?

**Comment by casbreuk** [comment]
Absolutely anything in C#.
I can double-click on a word and see it get highlighted, but it doesn't get that selected-outline around it, and doesn't appear any different in the minimap.  Atom is also not displaying any selection outline around any of the other matching text in the regular editor screen.  I do have minimap-highlight-selected installed, with Atom 1.3.0 (wasn't working in 1.2.4 either) on OSX.  

![atomnoselectionhighlight](https://cloud.githubusercontent.com/assets/2084492/11729397/b34077aa-9f54-11e5-9126-eacfe5d9d7fd.png)

**Comment by richrace** [comment]
Can you please tell me what settings you have in the `highlight-selected` package? 

Works here.

![highlighting](https://cloud.githubusercontent.com/assets/1273965/11729611/0708c6a2-9f88-11e5-98e3-463aad161761.gif)

**Comment by casbreuk** [comment]
It's either enabled or disabled.  There are no settings for it.
I have it enabled.

**Comment by richrace** [comment]
`minimap-highlight-selected` is a plugin for the minimap which uses the `highlight-selected` package. So you need both installed:

![screen shot 2015-12-10 at 22 07 15](https://cloud.githubusercontent.com/assets/1273965/11730055/8e3b7c12-9f8a-11e5-8aa6-f250054e73ea.png)
![screen shot 2015-12-10 at 22 08 17](https://cloud.githubusercontent.com/assets/1273965/11730060/9003ceb4-9f8a-11e5-90ab-3fa10ee0b282.png)
