### ISSUE TITLE
Highlight with one click

### ISSUE THREAD

**Issue by xErik** [richrace/highlight-selected#83]
Would it be technically possible to highlight a word(s) with just one click?

**Comment by richrace** [comment]
Anything is possible :wink: But yes it would be. However, this package replies on the selection event from atom core: 
https://github.com/richrace/highlight-selected/blob/master/lib/highlighted-area-view.coffee#L38-L43

So if we were to do it with a single click we'd need to implement or use the same the methods that the core uses to select.

**Comment by xErik** [comment]
I see. I will close this issue and have a look at it.
