### ISSUE TITLE
Feature request: PHP $ 'special case' should be an option

### ISSUE THREAD

**Issue by ezzatron** [richrace/highlight-selected#88]
I notice #80 added a special case for the $ in PHP variable names. I feel like this is counter-intuitive, because I would expect the word selection to be based purely upon the value of Atom's 'Non Word Characters'.

Is there a chance this could be made an optional feature instead?

**Comment by darianbr** [comment]
+1

**Comment by UltCombo** [comment]
+1 for using the same value as Atom's "Non Word Characters" setting.

**Comment by janhartigan** [comment]
Would be really nice to have this.

**Comment by richrace** [comment]
See #174
