### ISSUE TITLE
Highlight only when match found

### ISSUE THREAD

**Issue by dwelle** [richrace/highlight-selected#90]
Selected words should not be highlighted themselves when there is no other match found in buffer.

![image](https://cloud.githubusercontent.com/assets/5153846/8488635/5c72a7cc-2114-11e5-9ee4-567c7b42b688.png)

**Comment by richrace** [comment]
Have you set `hide highlight on selected word` in settings?

**Comment by dwelle** [comment]
I have. The issue was about when the option is `off`, and you highlight a word with just a single match in file. The use case being that you'd then know if what you highlighted also exists somewhere else in the file (without having to search for it).

But I noticed it's shown in the status bar:

![image](https://cloud.githubusercontent.com/assets/5153846/14935488/92dda2fa-0ed3-11e6-9308-b86a240fd88b.png)

So that makes the requested feature not so important → closing.
