### ISSUE TITLE
Counter for highlighted words

### ISSUE THREAD

**Issue by pkaske** [richrace/highlight-selected#94]
Thanks for making this awesome package! You make my life so much more easier.

What would make this package even more awesome is a counter in the status bar that shows a count of how many selections in the document were found.

What do you think?
Thanks again!

**Comment by josephpage** [comment]
This is already done.

**Comment by pkaske** [comment]
Sorry for the late reply.
I can't spot the counter in the status bar. Am I missing something?

![selection_035](https://cloud.githubusercontent.com/assets/11567985/10001045/1e95159a-60a0-11e5-8cb9-0f58a9a466dc.png)

**Comment by richrace** [comment]
Nope. Sorry, I haven't published the new version. 

Richard Race

**Comment by pkaske** [comment]
Aaah... Well that's a good reason why I cant find it :)
So then I'm just going to wait for the next release then.

Thank you
