### ISSUE TITLE
Don't highlight partial matches

### ISSUE THREAD

**Issue by imnickb** [richrace/highlight-selected#95]
For example, if I select int, don't highlight the word print.

**Comment by UltCombo** [comment]
In the plugin settings, tick the "Only Highlight Whole Words" option.

**Comment by jpillora** [comment]
thanks @UltCombo that's what I was looking for, @richrace maybe consider making that the default as that's how sublime works

**Comment by josephpage** [comment]
:+1:  for making "Only Highlight Whole Words" the default

**Comment by hmil** [comment]
+1 This feature is mainly used to keep track of occurences of a symbol therefore whole words by default makes more sense.

**Comment by karevn** [comment]
+1 It's more intuitive to use full matches by default

**Comment by richrace** [comment]
Done.

**Comment by hugollm** [comment]
Did partial matches get removed for good? I've tried disabling the "whole words" option but it had no effect whatsoever.
