### ISSUE TITLE
Change Text color of selected word

### ISSUE THREAD

**Issue by pratyushtewari** [richrace/highlight-selected#98]
I use high contrast to show the select highlight. I am overriding the selected-text background color in my styles.less to achive that. I am not able to find a way to change the color of the selected text.

See example.

<img width="152" alt="screen shot 2015-09-02 at 9 59 46 am" src="https://cloud.githubusercontent.com/assets/251768/9633198/8b2b5e18-5159-11e5-8735-70505168d4ba.png">

I want to do something like:

<img width="152" alt="screen shot 2015-09-02 at 9 59 46 ams" src="https://cloud.githubusercontent.com/assets/251768/9633287/0485bf2e-515a-11e5-8ea2-a6747966f2fd.png">

**Comment by richrace** [comment]
Yea that's a tricky one.

So, this package uses the decorations which are applied to a different layer. Inspect the elements and you'll see that the box is under `highlights` and then the text is within the `line`. 

I'm not sure if it will be possible. A thought I have would be to add text to the decoration and then colour with CSS but again, don't know if it's possible. 

I will have a think.

**Comment by 73** [comment]
Why is that closed? I am trying to do the same thing and found this closed issue. Is there something I do not see?

**Comment by pratyushtewari** [comment]
I moved on to vscode and closed this issue. 🤷🏻‍♂️

**Comment by 73** [comment]
But its still an issue for us who stuck with atom.
