### ISSUE TITLE
Feature Request: Create Cursors On Marked Areas

### ISSUE THREAD

**Issue by rolyataylor2** [richrace/highlight-selected#99]
Would be nice to be able to key-bind the ability to multi-cursor select-all marked ranges without the replace dialog for quick refactoring of variables or strings.

Also maybe the ability to limit the scope when the highlighted text is in the definition (more of a fork suggestion i think)

```
function whatever($variable) { /* limited to here */ }
```

I've been tweaking with the code to try to add in the ability to set multiple cursors at the words but haven't done well...  I added ::addCursorAtBufferPosition(range) to the regex section with no luck... Maybe get buffer by class name or something might work better... Anyway.

**Comment by Luminess** [comment]
+1
Also, have another hotkey to do the exact same thing but limiting the scope to the visible/on screen area.

**Comment by wlccgp3** [comment]
+1

**Comment by richrace** [comment]
See #174
